### ISSUE TITLE
CaseOLAP: MeSH full type path required in the query

### ISSUE THREAD

**Issue by xuanwang91** [shanzhenren/StructMineDataInfra#11]
CaseOLAP requires the MeSH full type path in the query, which is hard for users to use. Try change it to the most fine grained MeSH type.

**Comment by GentleZhu** [comment]
Now it support sub_string input of subtypes and target type. But user need to specify specific output type like Mesh:::xxxx (usually less than 15 chars).

**Comment by shanzhenren** [comment]
Hi Bran, could you fix this today as well?

Regards,
Xiang Ren


On Jul 29, 2017, at 12:24 PM, Bran <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #11<https://github.com/shanzhenren/StructMineDataInfra/issues/11>.
