### ISSUE TITLE
Network Exploration: some queries have no network returned

### ISSUE THREAD

**Issue by xuanwang91** [shanzhenren/StructMineDataInfra#12]
Queries are all entities and relations that should be found in our database. Some queries with no network returned:
Pharmacologic_Actions	Pharmacologic_Substance	has_mechanism_of_action

**Comment by mickeystroller** [comment]
The sample query is working now. Previously, it didn't work probably because of DB instability. Anyway, I add the signal to show the invalid query and query with no network returned. See commit: 8af445ca2892059881596e15f7484eb3d930a817
