### ISSUE TITLE
Network Exploration: networks are too small

### ISSUE THREAD

**Issue by xuanwang91** [shanzhenren/StructMineDataInfra#13]
The network returned are smaller than expected. For example, given the query (Genes, Diseases, process_involves_gene), the returned network has only 7 nodes, which is expected to be much larger. Not clear what is the use of "Number of edges"?

**Comment by shanzhenren** [comment]
@xuanwang91 this is because we have to limit the size of the visulized network to make the process efficient and the result easy to read. Users are expected to input "num of edges" to control this.

**Comment by mickeystroller** [comment]
If you want to issue multiple queries in Network Visualization page, please either refresh the page or switch to Distinctive Summarization page and then switch back. This can make sure the AngularJS will reload the data.
