### ISSUE TITLE
Make the "num of edges" and "num of papers" optional parameters

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#15]
Send backend default values if users do not input these two fields

**Comment by mickeystroller** [comment]
See commit: 9e102a10f70510d236f26d41d539a60cd8fa0b14

**Comment by shanzhenren** [comment]
Have you deployed this? It seems not working for now.

**Comment by mickeystroller** [comment]
This function should works. You can try the following query:

Argument1: Chemicals_and_Drugs
Argument2: Anatomy
Relation: is_associated_anatomy_of_gene_product

Notice some queries do not have a lot of relations and thus may not give enough edges.
