### ISSUE TITLE
Add query shuffle button

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#2]
For both interfaces, we should have a button to "shuffle" a query out of a given set, to auto-fill the query fields. This save time if do not want to type in queries.

**Comment by mickeystroller** [comment]
See commit: dcfa4bee071e03097695f20fb0bd5b9b6b47e13a

Stability test will be followed later.

**Comment by mickeystroller** [comment]
Tested.

**Comment by shanzhenren** [comment]
Have you updated with the query list that Xuan sent before? Please do so.

Regards,
Xiang Ren


On Jul 29, 2017, at 11:58 AM, Jiaming Shen <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/shanzhenren/StructMineDataInfra/issues/2>.
