### ISSUE TITLE
Change the window's title

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#26]
![image](https://user-images.githubusercontent.com/6671595/28751436-63d97cfe-74bc-11e7-8431-e4960e716921.png)

Change "Entity: XXX" to "Papers related to entity "**_XXX_**""
Change "Relation: AAA - BBB" to "Papers related to relationship between "**AAA**" and **"BBB"** "

**Comment by mickeystroller** [comment]
See the commit: 597064681df12ae06be39586b9f21659738180ad
