### ISSUE TITLE
Update the sub-title for both interfaces

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#27]
![image](https://user-images.githubusercontent.com/6671595/28798583-bc250b60-75f9-11e7-90ea-9812c2edd0be.png)

Put "Making sense of massive life science litrature - A "data-to-network-to-knowledge" system"

**Comment by mickeystroller** [comment]
See commit: 9a607a496a326b4cd995cc7551a9792a67149ae5

Currently, descriptions for both "network exploration" and "distinctive summarization" are the same. If that is your expected result, close this issue @shanzhenren
