### ISSUE TITLE
Predicted links show duplicated links

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#4]
![image](https://user-images.githubusercontent.com/6671595/28636353-b77e5f90-71f2-11e7-8299-a77e94ef1a12.png)

**Comment by shanzhenren** [comment]
Query: Nervous_System  Anatomy  has_nerve_supply

**Comment by mickeystroller** [comment]
Check commit 81204a3646eb08864656541ead3379afd7d16cbe
