### ISSUE TITLE
Show confidence score for newly predicted edges

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#5]
the score should be shown when mouse over the new edges

**Comment by GentleZhu** [comment]
Update query_prediction return types, fixed.

**Comment by mickeystroller** [comment]
Unable to implement the mouseover function. Instead, for a new predicted edge, click it and the confidence score will be shown in the pop-up windows. See commit: 92b07168fd13f958fe0a73430dd517950cb522b1

**Comment by shanzhenren** [comment]
@GentleZhu @mickeystroller This is a bit ugly. To make it better, we may include three papers that could "explain" this prediction. Here is an example, if we predict an edge (A, B) for em A and em B, then we show papers that mentions both A and B. 

Make sure you indicate "confidence score" and "related papers"

**Comment by shanzhenren** [comment]
@GentleZhu @mickeystroller this need to be done quickly as well.

![image](https://user-images.githubusercontent.com/6671595/28738677-b0804eca-73a9-11e7-8465-6c3518788070.png)

Remove the "title" in the confidence score filed. Add related papers.

**Comment by mickeystroller** [comment]
Fix the "title" in confidence score field. See commit: 50a4c24180978ad817d7f782a8864fb1b0bb04fe

For returning the paper explaining the prediction, currently the DB interface does not have that data, we can update it later. @GentleZhu

**Comment by shanzhenren** [comment]
the remaining issue has been listed in Issue #17
