### ISSUE TITLE
Return a notice if the result is empty

### ISSUE THREAD

**Issue by shanzhenren** [shanzhenren/StructMineDataInfra#9]
In both interfaces, handle the case where we find nothing match for the query; by returning something that notify users

**Comment by shanzhenren** [comment]
@mickeystroller please add this ASAP

**Comment by mickeystroller** [comment]
Now it will return a node with placeholder label "Invalid entity/relation type" or "No matched network" to notify the users. See commit: 8af445ca2892059881596e15f7484eb3d930a817
